add additional arguments to `publish-sdk`
Adds the ability to skip publishing a multi-arch manifest
(`--skip-manifest`) or publish a multi-arch manifest with remote images
that were pushed beforehand (`--only-manifest`).

Signed-off-by: Patrick J.P. Culp <jpculp@amazon.com>

diff --git a/publish-sdk b/publish-sdk
--- a/publish-sdk
+++ b/publish-sdk
@@ -3,6 +3,9 @@
 set -e -o pipefail
 shopt -qs failglob
 
+SKIP_MANIFEST="${SKIP_MANIFEST:-'false'}"
+ONLY_MANIFEST="${ONLY_MANIFEST:-'false'}"
+
 for opt in "$@"; do
    optarg="$(expr "${opt}" : '[^=]*=\(.*\)')"
    case "${opt}" in
@@ -10,12 +13,18 @@ for opt in "$@"; do
       --registry=*) REGISTRY="${optarg}" ;;
       --sdk-name=*) SDK_NAME="${optarg}" ;;
       --short-sha=*) SHORT_SHA="${optarg,,}" ;;
+      --skip-manifest=*) SKIP_MANIFEST="${optarg,,}" ;;
+      --only-manifest=*) ONLY_MANIFEST="${optarg,,}" ;;
    esac
 done
 
 for required_arg in VERSION REGISTRY SDK_NAME SHORT_SHA; do
   [ -z "${!required_arg}" ] && echo "${required_arg} not set!" >&2 && exit 1
 done
+
+if [[ "${SKIP_MANIFEST}" == "true" ]] && [[ "${ONLY_MANIFEST}" == "true" ]] ; then
+  echo "nothing to do" >&2 && exit 2
+fi
 
 update_image() {
   set -u
@@ -51,19 +60,24 @@ update_image() {
   local remote_host_arch_image="${remote_image}-${SHORT_SHA}-${host_arch}"
   local remote_alt_arch_image="${remote_image}-${SHORT_SHA}-${alt_arch}"
 
-  if ! docker image inspect "${local_host_arch_image}" >/dev/null 2>&1 ; then
-    echo "did not find ${local_host_arch_image}, skipping it ..." >&2
-    return
+  if [[ "${ONLY_MANIFEST}" != "true" ]]; then
+    if ! docker image inspect "${local_host_arch_image}" >/dev/null 2>&1 ; then
+      echo "did not find ${local_host_arch_image}, skipping it ..." >&2
+      return
+    fi
+
+    if ! docker tag "${local_host_arch_image}" "${remote_host_arch_image}" ; then
+      echo "failed to tag ${remote_host_arch_image}" >&2 && exit 1
+    fi
+
+    # push the image, if it exists locally
+    if ! docker push "${remote_host_arch_image}" ; then
+      echo "failed to push ${remote_host_arch_image}" >&2 && exit 1
+    fi
   fi
 
-  if ! docker tag "${local_host_arch_image}" "${remote_host_arch_image}" ; then
-    echo "failed to tag ${remote_host_arch_image}" >&2 && exit 1
-  fi
-
-  # push the image, if it exists locally
-  if ! docker push "${remote_host_arch_image}" ; then
-    echo "failed to push ${remote_host_arch_image}" >&2 && exit 1
-  fi
+  # return early to skip manifest generation steps
+  [[ "${SKIP_MANIFEST}" == "true" ]] && return
 
   # clean up any cached local copy of the manifest
   manifest_dir="${HOME}/.docker/manifests"
